### ISSUE TITLE
Requirement of phpunit/phpunit

### ISSUE THREAD

**Issue by BBrunekreeft** [WyriHaximus/php-compress#67]
In `composer.json`, phpunit/phpunit is now under the` require key`, wich installs phpunit in my production environment.
Shouldn't phpunit/phpunit be under the `require-dev` key?

**Comment by WyriHaximus** [comment]
Thanks for bringing this to my attention and providing a fix. This has been released as [`2.0.0`](https://github.com/WyriHaximus/php-compress/releases/tag/2.0.0).
